## build rules

TEX_DEPS = texheader.tex acknowledgements.tex revisionHistory.tex prettygloss.tex remark.tex appendixA.tex appendixB.tex glossarydefs.tex overview.tex nomencldef.tex SettingAndCharacters.tex GameplayMechanics.tex DOAs.tex FlightInterface.tex BaseInterface.tex AI.tex Technical.tex Art.tex Tools.tex Management.tex macros.tex

FIG_DEPS = 

BIB_DEPS = biblio.bib 

STY_DEPS = 

LMAKE = ../latexmakescripts/latex-make
NONBIB_DEPS = $(TEX_DEPS) $(FIG_DEPS) $(STY_DEPS) #$(ORG_DEPS)
